/**
 * 
 * Initial version of this code (c) 2009-2011 Media Tuners LLC with a full license to Pioneer Corporation.
 * 
 * Pioneer Corporation licenses this file to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 * 
 */


package net.zypr.api.enums;

public enum ManuverAction
{
  START,
  CONTINUE,
  STOP,
  ARRIVEFINISH,
  ARRIVEINTERMEDIATE,
  BEARLEFT,
  BEARLEFTTHENBEARLEFT,
  BEARLEFTTHENBEARRIGHT,
  BEARLEFTTHENTURNLEFT,
  BEARLEFTTHENTURNRIGHT,
  BEARRIGHT,
  BEARRIGHTTHENBEARLEFT,
  BEARRIGHTTHENBEARRIGHT,
  BEARRIGHTTHENTURNLEFT,
  BEARRIGHTTHENTURNRIGHT,
  BEARTHENKEEP,
  BEARTHENMERGE,
  DEPARTINTERMEDIATESTOP,
  DEPARTINTERMEDIATESTOPRETURNING,
  DEPARTSTART,
  ENTERROUNDABOUT,
  EXITROUNDABOUT,
  ENTERTHENEXITROUNDABOUT,
  KEEPLEFT,
  KEEPONRAMPLEFT,
  KEEPONRAMPRIGHT,
  KEEPONRAMPSTRAIGHT,
  KEEPRIGHT,
  KEEPSTRAIGHT,
  KEEPTOSTAYLEFT,
  KEEPTOSTAYRIGHT,
  KEEPTOSTAYSTRAIGHT,
  MERGE,
  NONE,
  RAMPTHENHIGHWAYLEFT,
  RAMPTHENHIGHWAYRIGHT,
  RAMPTHENHIGHWAYSTRAIGHT,
  ROADNAMECHANGE,
  TAKE,
  TAKERAMPLEFT,
  TAKERAMPRIGHT,
  TAKERAMPSTRAIGHT,
  TAKETRANSIT,
  TRANSFER,
  TRANSITARRIVE,
  TRANSITDEPART,
  TURNBACK,
  TURNLEFT,
  TURNLEFTTHENBEARLEFT,
  TURNLEFTTHENBEARRIGHT,
  TURNLEFTTHENTURNLEFT,
  TURNLEFTTHENTURNRIGHT,
  TURNRIGHT,
  TURNRIGHTTHENBEARLEFT,
  TURNRIGHTTHENBEARRIGHT,
  TURNRIGHTTHENTURNLEFT,
  TURNRIGHTTHENTURNRIGHT,
  TURNTHENMERGE,
  TURNTOSTAYLEFT,
  TURNTOSTAYRIGHT,
  UNKNOWN,
  UTURN,
  WAIT,
  WALK,
  ARRIVEINTERMEDIATESTOP,
  RAMPTOHIGHWAYSTRAIGHT;
}
